//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectOffice.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.Task = new HashSet<Task>();
        }
    
        public int Id { get; set; }
        public string FullTitle { get; set; }
        public string Icon { get; set; }
        public System.DateTime CreatedTime { get; set; }
        public System.DateTime DeletedTime { get; set; }
        public System.DateTime StartScheduledDate { get; set; }
        public System.DateTime FinishScheduledDate { get; set; }
        public string Description { get; set; }
        public int CreatorEmployeeId { get; set; }
        public int ResponsibleEmplyeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Task { get; set; }
    }
}
